# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdae61ff3ec987d6435a5b26b20864a6f656f2507e7d42439b7273253108666a8853c332208a965bbe592bd17b45ed76801d67827535d34b5682ee20a3d08dc1

test:
  secret_key_base: 2db2fcb98c228e8b3b036445852e85e648a58c1bdd9ec3dd383d492ef909f9da82a00b615ebc87cd48584985988e961d929649bb4655915ecaf3ac61e3696589

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
